
const $=id=>document.getElementById(id),fmt=n=>Number(n||0).toLocaleString('ar-EG',{maximumFractionDigits:2});
const safeJSON=(key,fallback)=>{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch(_){try{localStorage.removeItem(key)}catch(__){};return fallback}};
const setJSON=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch(_){return false}};
let prices=safeJSON('bushra_live_prices_v123',{24:0,21:0,18:0,buy24:0,buy21:0,buy18:0}),path=[];
let products=safeJSON('bushra_products_v6',null)||[
{id:1,company:'Egypt Gold',type:'غوايش',style:'غويشة مخصوص',name:'يونكة',code:'EG-B-001',karat:21,weight:5.25,making:0,img:'assets/shop.jpg'},
{id:2,company:'Egypt Gold',type:'غوايش',style:'غويشة مخصوص',name:'دب',code:'EG-B-002',karat:21,weight:6.10,making:0,img:'assets/shop.jpg'},
{id:3,company:'Egypt Gold',type:'غوايش',style:'غويشة مخصوص',name:'عصفورة',code:'EG-B-003',karat:21,weight:4.80,making:0,img:'assets/shop.jpg'},
{id:4,company:'Egypt Gold',type:'غوايش',style:'غويشة مخصوص',name:'زيجاج',code:'EG-B-004',karat:21,weight:7.20,making:0,img:'assets/shop.jpg'},
{id:5,company:'Egypt Gold',type:'خواتم',style:'خواتم يومية',name:'خاتم كلاسيك',code:'EG-R-001',karat:18,weight:3.20,making:0,img:'assets/shop.jpg'}];
let bullionOffers=safeJSON('bushra_bullion_v6',[]),reports=safeJSON('bushra_reports_v6',[]);
function saveAll(){setJSON('bushra_products_v6',products);setJSON('bushra_bullion_v6',bullionOffers);setJSON('bushra_reports_v6',reports)}
function toast(t){const x=$('toast');x.textContent=t;x.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.style.display='none',3000)}
function openMenu(){$('side').classList.add('open')}function closeMenu(){$('side').classList.remove('open')}function toggleGroup(btn){btn.parentElement.classList.toggle('open')}
function showSection(id){if(id==='home'){window.scrollTo({top:0,behavior:'smooth'});return}const x=$(id);if(x)x.scrollIntoView({behavior:'smooth',block:'start'})}
function scrollToId(id){closeMenu();if(id==='prices'){document.getElementById('prices')?.scrollIntoView({behavior:'smooth',block:'start'});return}showSection(id)}
function openCatalog(type){path=[];showSection('bullionCatalog');renderCatalog(type);closeMenu()}
function imgFor(type){return 'assets/shop.jpg'}
function renderCatalog(filterType=''){
 const companies=[...new Set(products.map(p=>p.company))];let items=products;
 if(filterType)items=items.filter(p=>p.type===filterType);
 const catalog=$('catalog'),grid=$('productGrid');grid.innerHTML='';$('crumbs').innerHTML=filterType?`<button class="crumb active" onclick="renderCatalog()">${filterType}</button>`:'';
 if(!filterType){catalog.innerHTML=companies.map(c=>`<div class="tile" onclick="renderCompany('${escapeHtml(c)}')"><div class="tileImg" style="background-image:url('${imgFor('')}')"></div><h3>${c}</h3><small>${products.filter(p=>p.company===c).length} منتج</small></div>`).join('')||'<div class="empty">أضف المنتجات من لوحة الإدارة</div>';return}
 catalog.innerHTML=[...new Set(items.map(p=>p.style))].map(s=>`<div class="tile" onclick="renderStyle('${escapeHtml(filterType)}','${escapeHtml(s)}')"><div class="tileImg" style="background-image:url('${imgFor(filterType)}')"></div><h3>${s}</h3><small>${items.filter(p=>p.style===s).length} موديل</small></div>`).join('');
}
function renderCompany(c){const items=products.filter(p=>p.company===c);$('crumbs').innerHTML=`<button class="crumb" onclick="renderCatalog()">الشركات</button><button class="crumb active">${c}</button>`;$('catalog').innerHTML=[...new Set(items.map(p=>p.type))].map(t=>`<div class="tile" onclick="renderType('${escapeHtml(c)}','${escapeHtml(t)}')"><div class="tileImg" style="background-image:url('${imgFor(t)}')"></div><h3>${t}</h3><small>${items.filter(p=>p.type===t).length} منتج</small></div>`).join('');$('productGrid').innerHTML=''}
function renderType(c,t){const items=products.filter(p=>p.company===c&&p.type===t);$('crumbs').innerHTML=`<button class="crumb" onclick="renderCompany('${escapeHtml(c)}')">${c}</button><button class="crumb active">${t}</button>`;$('catalog').innerHTML=[...new Set(items.map(p=>p.style))].map(s=>`<div class="tile" onclick="renderStyle('${escapeHtml(t)}','${escapeHtml(s)}','${escapeHtml(c)}')"><div class="tileImg" style="background-image:url('${imgFor(t)}')"></div><h3>${s}</h3><small>${items.filter(p=>p.style===s).length} موديل</small></div>`).join('');$('productGrid').innerHTML=''}
function renderStyle(t,s,c=''){const items=products.filter(p=>(!c||p.company===c)&&p.type===t&&p.style===s);$('crumbs').innerHTML=`<button class="crumb" onclick="renderType('${escapeHtml(c||items[0]?.company||'')}','${escapeHtml(t)}')">${t}</button><button class="crumb active">${s}</button>`;$('catalog').innerHTML='';$('productGrid').innerHTML=items.map(productCard).join('')||'<div class="empty">لا توجد منتجات في هذه المجموعة.</div>'}
function productCard(p){const sell=(prices[p.karat]||0)*p.weight+(Number(p.making)||0),saved=safeJSON('bushra_saved',[]).includes(p.id);return `<article class="product"><div class="productImg" style="background-image:url('${p.img||'assets/shop.jpg'}')"></div><div class="productBody"><span class="pill">${p.company}</span><h3>${p.name}</h3><div class="meta"><div>الوزن<br><b>${fmt(p.weight)} جم</b></div><div>العيار<br><b>${p.karat}</b></div><div>الكود<br><b>${p.code||'—'}</b></div><div>السعر الحالي<br><b>${sell?fmt(sell)+' ج.م':'يتحدث الآن'}</b></div></div><div class="productBtns"><button class="buyBtn" onclick="openPurchase(${p.id})">شراء الآن</button><button class="reserveBtn" onclick="reserveProduct(${p.id})">حجز 24 ساعة</button><button class="saveBtn" onclick="saveProduct(${p.id})">${saved?'★ محفوظ':'☆ حفظ'}</button></div></div></article>`}
function saveProduct(id){let a=safeJSON('bushra_saved',[]);a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem('bushra_saved',JSON.stringify(a));toast(a.includes(id)?'تم حفظ المنتج':'تمت إزالة المنتج من المحفوظات');renderStyle(products.find(p=>p.id===id).type,products.find(p=>p.id===id).style,products.find(p=>p.id===id).company)}
function reserveProduct(id){if(!requireCustomer('للحجز 24 ساعة لازم يكون عندك حساب موثق في الموقع.'))return;const p=products.find(x=>x.id===id),r={id:'R-'+Date.now(),productId:id,code:p.code,name:p.name,expires:Date.now()+86400000};const u=getCustomer();orders.unshift({id:r.id,type:'حجز',status:'pending_review',createdAt:new Date().toISOString(),customerRef:u.id,customerName:u.name,phone:u.phone,customerEmail:u.email,productId:p.id,productCode:p.code,productName:p.name,company:p.company,productType:p.type,style:p.style,karat:p.karat,weight:p.weight,pricePerGram:prices[p.karat]||0,total:(prices[p.karat]||0)*p.weight+(Number(p.making)||0)});saveOrders();const msg=encodeURIComponent(`طلب حجز 24 ساعة\nكود المنتج: ${p.code}\nالمنتج: ${p.name}\nالوزن: ${p.weight} جم\nالعيار: ${p.karat}\nرقم الحجز: ${r.id}\nالعميل: ${u.name}`);const wa=localStorage.getItem('bushra_whats')||'';toast('تم إرسال طلب الحجز للمراجعة — لا يتم تثبيته قبل موافقة المحل');if(wa)window.open('https://wa.me/'+wa+'?text='+msg,'_blank');renderMyOrders()}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderBullion(){const el=$('bullionOffers');el.innerHTML=bullionOffers.filter(x=>x.status!=='closed').map(x=>`<div class="tile"><div class="tileImg" style="background-image:url('${x.image||'assets/shop.jpg'}')"></div><h3>${escapeHtml(x.alias)}</h3><small>${x.weight} جم • عيار ${x.karat}</small><p class="small">كود العرض: <b>${x.code}</b></p><button class="btn primary" onclick="document.getElementById('bullionRequestCode').value='${x.code}';toast('تم اختيار العرض ${x.code}')">أطلب العرض</button></div>`).join('')||'<div class="empty">لا توجد عروض منشورة حاليًا.</div>'}
function requestBullion(){const code=$('bullionRequestCode').value.trim(),weight=$('bullionRequestWeight').value,phone=$('bullionRequestPhone').value.trim();if(!code||!phone)return toast('اكتب رقم العرض ووسيلة التواصل');const msg=encodeURIComponent(`طلب سبيكة عبر الوسيط\nكود العرض: ${code}\nالوزن المطلوب: ${weight||'حسب العرض'} جم\nالتواصل: ${phone}`);const wa=localStorage.getItem('bushra_whats')||'';if(wa)window.open('https://wa.me/'+wa+'?text='+msg,'_blank');toast('تم تسجيل طلبك لدى الوسيط')}
function sellFromVault(){if(!requireCustomer('بيع الذهب من المحفظة متاح فقط لصاحب الحساب.'))return;const w=prompt('كم جرام تريد بيعها؟','1');if(!w)return;const have=Number(localStorage.getItem('bushra_customer_vault_weight')||0);if(Number(w)<=0||Number(w)>have)return toast('الكمية أكبر من رصيدك الحالي');toast('تم تجهيز طلب بيع '+w+' جم بسعر الشراء الحالي — بانتظار مراجعة الإدارة')}
function getCustomer(){return safeJSON('bushra_customer',null)}
function requireCustomer(message){if(getCustomer())return true;toast(message||'سجّل حسابك أولًا لإتمام العملية');openAccount();return false}
function openAccount(){const u=getCustomer();$('accountModal').classList.add('open');$('accountForm').style.display=u?'none':'block';$('accountLogged').classList.toggle('hidden',!u);$('accountTitle').textContent=u?'👤 حسابي':'👤 إنشاء حساب';if(u){$('accountNameView').textContent=u.name;$('accountEmailView').textContent=u.email;$('accountPhoneView').textContent=u.phone;renderMyOrders()}}
function closeAccount(){$('accountModal').classList.remove('open')}
function demoLogin(){const u={id:'DEMO-'+Date.now().toString(36).toUpperCase(),name:'عميل تجريبي',phone:'01000000000',email:'demo@bushra.local',createdAt:new Date().toISOString()};setJSON('bushra_customer',u);toast('تم الدخول بحساب تجريبي للمعاينة');openAccount();renderVault()}
on('accountForm','submit',async e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.target).entries());const u={id:'CUS-'+Date.now().toString(36).toUpperCase(),name:fd.name.trim(),phone:fd.phone.trim(),email:fd.email.trim().toLowerCase(),createdAt:new Date().toISOString()};setJSON('bushra_customer',u);localStorage.setItem('bushra_customer_vault_weight','0');localStorage.setItem('bushra_customer_vault_cost','0');try{await fetch('/api/customers',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(u)})}catch(_){}toast('تم إنشاء الحساب — سنرسل تأكيد البريد عند تفعيل البريد الإنتاجي');e.target.reset();openAccount();renderVault()})
function logoutCustomer(){localStorage.removeItem('bushra_customer');closeAccount();renderVault();toast('تم تسجيل الخروج')}
function renderMyOrders(){const u=getCustomer(),el=$('myOrders');if(!u||!el)return;const mine=orders.filter(o=>o.customerRef===u.id);el.innerHTML='<h3>طلباتي</h3>'+(mine.map(o=>`<div class="row"><span><b>${escapeHtml(o.id)}</b><br><small>${escapeHtml(o.type||'طلب')} • ${escapeHtml(o.productName||'')}</small></span><span class="status">${escapeHtml(o.status||'pending')}</span></div>`).join('')||'<div class="empty">لا توجد طلبات حتى الآن.</div>')}
async function loadPrices(manual=false){
 const status=$('liveStatus'),top=$('topLive'),updated=$('priceUpdated');
 try{
  if(status)status.textContent='🟡 جاري تحديث الأسعار...';
  let r,d;
  try{
   r=await withTimeout(fetch('/api/gold?ts='+Date.now(),{cache:'no-store'}),7000);
   d=await withTimeout(r.json(),7000);
   if(!r.ok)throw new Error(d.error||'server_gold_failed');
  }catch(_){
   d=await fetchDirectFormula();
  }
  const next={24:Number(d.prices['24'].sell),21:Number(d.prices['21'].sell),18:Number(d.prices['18'].sell),buy24:Number(d.prices['24'].buy),buy21:Number(d.prices['21'].buy),buy18:Number(d.prices['18'].buy)};
  if(!Object.values(next).every(Number.isFinite)||!next[21])throw new Error('invalid_price_payload');
  prices=next;setJSON('bushra_live_prices_v123',prices);
  [['sell24',prices[24]],['buy24',prices.buy24],['sell21',prices[21]],['buy21',prices.buy21],['sell18',prices[18]],['qBuy21',prices.buy21],['qSell21',prices[21]],['sellGoldRate',prices.buy21]].forEach(([id,v])=>{const el=$(id);if(el)el.textContent=fmt(v)+' ج.م'});
  if(status)status.textContent='🟢 سعر مباشر'; if(top)top.textContent='🟢 مباشر';
  if(updated)updated.textContent='آخر تحديث '+new Date(d.updatedAt||Date.now()).toLocaleTimeString('ar-EG',{hour12:false,timeZone:'Africa/Cairo'});
  renderCatalog();renderBullionCatalog();
  if(manual)toast('تم تحديث الأسعار');
 }catch(e){
  const cached=safeJSON('bushra_live_prices_v123',null);
  if(cached&&cached[21]){prices=cached;[['sell24',prices[24]],['buy24',prices.buy24],['sell21',prices[21]],['buy21',prices.buy21],['sell18',prices[18]],['qBuy21',prices.buy21],['qSell21',prices[21]],['sellGoldRate',prices.buy21]].forEach(([id,v])=>{const el=$(id);if(el)el.textContent=fmt(v)+' ج.م'});if(status)status.textContent='🟠 آخر سعر محفوظ';if(top)top.textContent='🟠 محفوظ';if(updated)updated.textContent='آخر سعر محفوظ مؤقتًا';renderCatalog();renderBullionCatalog();if(manual)toast('تعذر المصدر المباشر؛ تم عرض آخر سعر محفوظ')}
  else{if(status)status.textContent='🔴 تعذر تحديث السعر';if(top)top.textContent='تعذر التحديث';if(updated)updated.textContent='لم يتوفر سعر بعد'}
 }
}
async function loadWorld(){try{const r=await withTimeout(fetch('/api/world?ts='+Date.now(),{cache:'no-store'}),7000);if(!r.ok)throw new Error('world_http_'+r.status);const d=await withTimeout(r.json(),7000);$('worldGold').textContent=d.price?'$'+Number(d.price).toLocaleString('en-US',{maximumFractionDigits:2})+'/oz':'غير متاح';$('worldSilver').textContent=d.silver?'$'+Number(d.silver).toLocaleString('en-US',{maximumFractionDigits:2})+'/oz':'غير متاح';$('worldChange').textContent=(d.changePct!==undefined&&d.changePct!==null)?((Number(d.changePct)>=0?'+':'')+Number(d.changePct).toFixed(2)+'%'):'غير متاح';$('worldDxy').textContent=d.dxy?Number(d.dxy).toFixed(2):'غير متاح';$('worldUpdated').textContent='آخر تحديث: '+new Date(d.updatedAt||Date.now()).toLocaleString('ar-EG');$('worldSource').textContent='المصدر: '+(d.source||'مصدر البيانات')}catch(e){$('worldGold').textContent=$('worldSilver').textContent=$('worldChange').textContent=$('worldDxy').textContent='غير متاح';$('worldSource').textContent='تعذر تحديث المصدر الآن'}}
function updateClock(){const t=new Intl.DateTimeFormat('ar-EG',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false,timeZone:'Africa/Cairo'}).format(new Date());const el=$('clock');if(el)el.textContent='القاهرة '+t}
function on(id,event,handler){const el=$(id);if(el)el.addEventListener(event,handler)}
function withTimeout(promise,ms=7000){return Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('timeout')),ms))])}
async function fetchDirectFormula(){
 const gold=await withTimeout(fetch('https://api.gold-api.com/price/XAU',{cache:'no-store'}),7000);
 const gd=await gold.json();
 const usdPerOz=Number(gd.price??gd.value??gd.amount);
 if(!Number.isFinite(usdPerOz)||usdPerOz<=0)throw new Error('bad_gold_source');
 let fx;
 try{fx=await withTimeout(fetch('https://api.frankfurter.dev/v2/rate/USD/EGP?providers=CBE',{cache:'no-store'}),7000)}catch(_){fx=await withTimeout(fetch('https://api.frankfurter.dev/v2/rate/USD/EGP',{cache:'no-store'}),7000)}
 const fd=await fx.json();const usdEgp=Number(fd.rate);
 if(!Number.isFinite(usdEgp)||usdEgp<=0)throw new Error('bad_fx_source');
 const base21=usdPerOz*usdEgp/35.55,base24=base21*24/21,base18=base21*18/21;
 const spread=20;
 return {prices:{24:{sell:base24+spread/2,buy:Math.max(0,base24-spread/2)},21:{sell:base21+spread/2,buy:Math.max(0,base21-spread/2)},18:{sell:base18+spread/2,buy:Math.max(0,base18-spread/2)}},updatedAt:gd.updatedAt||new Date().toISOString(),source:'مصدر مباشر احتياطي'};
}

on('sellImages','change',e=>previewFiles(e.target.files,'sellPreview'));function previewFiles(files,id){const p=$(id);p.innerHTML='';[...files].slice(0,12).forEach(f=>{const r=new FileReader();r.onload=()=>p.insertAdjacentHTML('beforeend',`<img src="${r.result}">`);r.readAsDataURL(f)})}
on('sellForm','submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());d.alias='بائع رقم '+String(Math.floor(Math.random()*90)+10);try{const r=await fetch('/api/offers',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)});if(!r.ok)throw 0;toast('تم إرسال العرض للمراجعة');e.target.reset()}catch(e){toast('تم تجهيز العرض محليًا للمراجعة؛ اربطه بالخادم عند التشغيل')}})
on('bullionForm','submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());d.code=d.code||'B-'+String(Date.now()).slice(-6);d.status='pending';d.createdAt=new Date().toISOString();bullionOffers.unshift(d);saveAll();renderBullion();e.target.reset();toast('تم حفظ عرض السبيكة للمراجعة')});
on('lostForm','submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());d.id='L-'+String(Date.now()).slice(-6);d.status='pending';d.createdAt=new Date().toISOString();reports.unshift(d);saveAll();renderReports();e.target.reset();toast('تم إرسال البلاغ للمراجعة قبل النشر')});
function renderReports(){const publicList=reports.filter(x=>x.status==='published');$('lostList').innerHTML=publicList.map(x=>`<div class="row"><div><b>${x.id}</b><br><span class="small">${escapeHtml(x.description)}</span></div><span class="status">بلاغ منشور</span></div>`).join('')||'<div class="empty">لا توجد بلاغات منشورة.</div>'}
async function openAdmin(){ $('admin').classList.add('open'); $('adminLogin').classList.add('hidden'); $('adminBody').classList.add('hidden'); try{const r=await fetch('/api/admin/data',{cache:'no-store'}); if(r.ok){$('adminBody').classList.remove('hidden');renderAdmin();syncAdminData();}else{$('adminLogin').classList.remove('hidden');$('adminPass').focus();}}catch(e){$('adminLogin').classList.remove('hidden');$('adminPass').focus();} } function closeAdmin(){$('admin').classList.remove('open')}async function logoutAdmin(){try{await fetch('/api/admin/logout',{method:'POST'});}catch(e){}$('adminLogin').classList.remove('hidden');$('adminBody').classList.add('hidden');toast('تم تسجيل الخروج')}

async function syncAdminData(){try{const r=await fetch('/api/admin/data',{cache:'no-store'});if(!r.ok)return;const d=await r.json();if(Array.isArray(d.customers)){window.adminCustomers=d.customers||[];renderAdminCustomers()} if(Array.isArray(d.orders)&&d.orders.length){orders=d.orders.map(o=>({id:o.order_code||('ORD-'+o.id),type:o.order_type,status:o.status,createdAt:o.created_at,customerRef:o.customer_ref,customerName:o.customer_name,phone:o.phone,delivery:o.delivery,notes:o.notes,productId:o.product_id,productCode:o.product_code,productName:o.product_name,company:o.company,productType:o.product_type,style:o.style,karat:o.karat,weight:o.weight,pricePerGram:o.price_per_gram,total:o.total_amount}));saveOrders();renderAdminOrders()}}catch(e){}}
async function loginAdmin(){const password=$('adminPass').value;try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password})});if(!r.ok)throw 0;$('adminLogin').classList.add('hidden');$('adminBody').classList.remove('hidden');renderAdmin();syncAdminData();toast('تم الدخول للوحة الإدارة')}catch(e){toast('كلمة المرور غير صحيحة')}}
function adminTab(id){document.querySelectorAll('.adminSec').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');if(id==='aOrders')renderAdminOrders();if(id==='aCustomers')renderAdminCustomers();if(id==='aOffers')renderAdminBullion();if(id==='aReports')renderAdminReports()}
on('apImgs','change',e=>previewFiles(e.target.files,'apPreview'));
function addAdminProduct(){const files=[...$('apImgs').files];const p={id:Date.now(),company:$('apCompany').value.trim(),type:$('apType').value.trim(),style:$('apStyle').value.trim(),name:$('apName').value.trim(),code:$('apCode').value.trim()||'P-'+Date.now(),karat:Number($('apK').value),weight:Number($('apW').value),making:Number($('apM').value||0),img:'assets/shop.jpg',images:[]};if(!p.name||!p.weight)return toast('أدخل اسم المنتج والوزن');if(files.length){let done=0;files.forEach(f=>{const r=new FileReader();r.onload=()=>{p.images.push(r.result);done++;if(done===files.length){p.img=p.images[0];products.unshift(p);saveAll();renderAdmin();renderCatalog();$('apPreview').innerHTML='';$('apImgs').value='';toast('تمت إضافة المنتج والصور')}};r.readAsDataURL(f)})}else{products.unshift(p);saveAll();renderAdmin();renderCatalog();toast('تمت إضافة المنتج')}}
function renderAdmin(){renderAdminOrders();renderAdminCustomers();renderAdminProducts();renderAdminBullion();renderAdminReports()}
window.adminCustomers=[];function renderAdminCustomers(){const el=$('adminCustomers');if(!el)return;const a=window.adminCustomers||[];el.innerHTML=a.map(c=>`<div class="adminRow"><div><b>${escapeHtml(c.name)}</b><div class="small">${escapeHtml(c.email)} • ${escapeHtml(c.phone)}</div><div class="small">${c.created_at?new Date(c.created_at).toLocaleString('ar-EG'):''}</div></div><span class="status">${escapeHtml(c.status||'pending_verification')}</span></div>`).join('')||'<div class="empty">لا توجد حسابات محفوظة في قاعدة البيانات بعد.</div>'}
function renderAdminProducts(){$('adminProducts').innerHTML=products.map(p=>`<div class="adminRow"><div><b>${escapeHtml(p.name)}</b><div class="small">${escapeHtml(p.company)} • ${escapeHtml(p.type)} • ${escapeHtml(p.style)} • ${p.weight} جم • ${p.code}</div></div><button class="btn light danger" onclick="deleteProduct(${p.id})">حذف</button></div>`).join('')}
function deleteProduct(id){products=products.filter(p=>p.id!==id);saveAll();renderAdminProducts();renderCatalog();toast('تم حذف المنتج')}
function renderAdminBullion(){$('adminBullion').innerHTML=bullionOffers.map((x,i)=>`<div class="adminRow"><div><b>${x.alias}</b><div class="small">${x.code} • ${x.weight} جم • ${x.status}</div></div><div><button class="btn light" onclick="publishBullion(${i})">نشر</button><button class="btn light danger" onclick="bullionOffers.splice(${i},1);saveAll();renderAdminBullion();renderBullion()">حذف</button></div></div>`).join('')||'<div class="empty">لا توجد عروض.</div>'}
function publishBullion(i){bullionOffers[i].status='published';saveAll();renderAdminBullion();renderBullion();toast('تم نشر عرض السبيكة بدون إظهار سعرها')}
function renderAdminReports(){$('adminReports').innerHTML=reports.map((x,i)=>`<div class="adminRow"><div><b>${x.id}</b><div class="small">${escapeHtml(x.description)} • ${x.phone}</div></div><div><button class="btn light" onclick="publishReport(${i})">نشر</button><button class="btn light danger" onclick="reports.splice(${i},1);saveAll();renderAdminReports();renderReports()">حذف</button></div></div>`).join('')||'<div class="empty">لا توجد بلاغات.</div>'}
function publishReport(i){reports[i].status='published';saveAll();renderAdminReports();renderReports();toast('تم نشر البلاغ')}
function saveAdminSettings(){localStorage.setItem('bushra_whats',$('setWhats').value.trim());localStorage.setItem('bushra_shop',$('setShop').value.trim());localStorage.setItem('bushra_making',$('setMaking').value);toast('تم حفظ إعدادات العرض')}
function importCSV(){const f=$('csvFile').files[0];if(!f)return toast('اختر ملف CSV');const r=new FileReader();r.onload=()=>{const lines=r.result.split(/\r?\n/).filter(Boolean),head=lines.shift().split(',').map(x=>x.trim());let count=0;for(const line of lines){const v=line.split(',');const o={};head.forEach((h,i)=>o[h]=v[i]?.trim()||'');if(!o.name)continue;products.unshift({id:Date.now()+count,company:o.company||'Egypt Gold',type:o.type||'مجوهرات',style:o.style||'عام',name:o.name,code:o.code||('P-'+Date.now()+count),karat:Number(o.karat||21),weight:Number(o.weight||0),making:Number(o.making||0),img:o.image||'assets/shop.jpg'});count++}saveAll();renderAdmin();renderCatalog();toast('تم استيراد '+count+' منتج')};r.readAsText(f)}
let orders=safeJSON('bushra_orders_v8',[]);
function saveOrders(){setJSON('bushra_orders_v8',orders)}
function openPurchase(id){if(!requireCustomer('للشراء لازم تنشئ حسابًا حتى لا يمكن استخدام أرقام وهمية.'))return;const p=products.find(x=>x.id===id);if(!p)return;const sell=(prices[p.karat]||0)*p.weight+(Number(p.making)||0);$('purchaseProductId').value=id;$('purchaseSummary').innerHTML=`<div class="orderStat"><small>المنتج</small><b>${escapeHtml(p.name)}</b></div><div class="orderStat"><small>الشركة</small><b>${escapeHtml(p.company)}</b></div><div class="orderStat"><small>الوزن / العيار</small><b>${fmt(p.weight)} جم / ${p.karat}</b></div><div class="orderStat"><small>السعر الحالي</small><b>${sell?fmt(sell)+' ج.م':'يتحدث الآن'}</b></div>`;$('purchaseAccountBox').innerHTML=`👤 الحساب: <b>${escapeHtml(getCustomer()?.name||'')}</b> • ${escapeHtml(getCustomer()?.email||'')} • سيتم ربط الطلب بهذا الحساب`;$('purchaseModal').classList.add('open')}
function closePurchase(){$('purchaseModal').classList.remove('open')}
on('purchaseForm','submit',async e=>{e.preventDefault();const p=products.find(x=>x.id===Number($('purchaseProductId').value));if(!p)return;const fd=Object.fromEntries(new FormData(e.target).entries());const u=getCustomer();if(!u){closePurchase();return requireCustomer('سجّل حسابك أولًا.')}fd.customerName=u.name;fd.phone=u.phone;const amount=(prices[p.karat]||0)*p.weight+(Number(p.making)||0);const order={id:'ORD-'+Date.now().toString().slice(-8),type:'شراء',status:'pending_review',createdAt:new Date().toISOString(),customerRef:u.id,customerEmail:u.email,customerName:fd.customerName,phone:fd.phone,delivery:fd.delivery,notes:fd.notes,productId:p.id,productCode:p.code,productName:p.name,company:p.company,productType:p.type,style:p.style,karat:p.karat,weight:p.weight,pricePerGram:prices[p.karat]||0,total:amount};orders.unshift(order);saveOrders();try{const r=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(order)});if(!r.ok)throw 0}catch(_){}closePurchase();e.target.reset();toast('تم إرسال الطلب للمراجعة — رقم الطلب '+order.id);renderMyOrders();});
function renderAdminOrders(){const el=$('adminOrders');if(!el)return;const sorted=[...orders].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));el.innerHTML=sorted.map(o=>`<div class="adminRow"><div><b>${o.id} • ${escapeHtml(o.type||'شراء')}</b><div class="small">${escapeHtml(o.customerName||o.customerRef||'عميل')} • ${escapeHtml(o.phone||'')} • ${escapeHtml(o.productName||'')} • ${o.weight||0} جم • ${fmt(o.total||0)} ج.م</div><div class="small">${new Date(o.createdAt).toLocaleString('ar-EG')}</div></div><div class="contactLinks"><span class="status">${escapeHtml(o.status==='pending_review'?'بانتظار المراجعة':(o.status==='completed'?'تمت المعالجة':(o.status||'جديد')))}</span>${o.phone?`<a class="btn light" href="https://wa.me/${String(o.phone).replace(/\D/g,'')}?text=${encodeURIComponent('بخصوص طلبك '+o.id+' لدى عبدالله بشرى')}" target="_blank" rel="noopener">واتساب</a>`:''}<button class="btn light" onclick="markOrderDone('${o.id}')">تمت المعالجة</button></div></div>`).join('')||'<div class="empty">لا توجد طلبات بعد.</div>';const badge=$('adminOrderBadge');if(badge){const n=orders.filter(o=>o.status==='new').length;badge.textContent=n;badge.style.display=n?'inline-flex':'none'}}
async function markOrderDone(id){const o=orders.find(x=>x.id===id);if(!o)return;o.status='completed';saveOrders();try{await fetch('/api/admin/order-status',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({orderCode:id,status:'completed'})})}catch(_){}renderAdminOrders();toast('تم تحديث حالة الطلب')}
function refreshAdminOrders(){renderAdminOrders();toast('تم تحديث الطلبات')}
function renderVault(){const u=getCustomer();const locked=!u;$('vaultLocked').style.display=locked?'block':'none';$('vaultIntro').textContent=locked?'المحفظة مرتبطة بحساب العميل، ولا يوجد رصيد قبل تسجيل الدخول وامتلاك ذهب محفوظ.':'محفظتك مرتبطة بحسابك وطلباتك، وأي زيادة في الرصيد يجب أن تنتج عن عملية معتمدة.';const weight=locked?0:Number(localStorage.getItem('bushra_customer_vault_weight')||0),cost=locked?0:Number(localStorage.getItem('bushra_customer_vault_cost')||0),value=weight*(prices.buy24||0);$('vaultWeight').textContent=fmt(weight)+' جم';$('vaultCost').textContent=fmt(cost)+' ج.م';$('vaultValue').textContent=fmt(value)+' ج.م';$('vaultPL').textContent=fmt(value-cost)+' ج.م'}
function openPrivacy(){openArticle('الخصوصية والأمان',`<p>بيانات العميل والبائع لا تُعرض للطرف الآخر. بيانات التواصل الخاصة تظل للإدارة، والطلبات تسجل برقم عملية واضح.</p><h3>حماية الإدارة</h3><p>لوحة الإدارة غير موجودة في قائمة الموقع العامة. الدخول يعتمد على جلسة خادم، ومع التشغيل النهائي نضيف Passkey ببصمة أو Face ID بدل الاعتماد على كلمة المرور وحدها.</p><h3>مهم</h3><p>لا يوجد نظام إنترنت مضمون بنسبة 100%، لذلك نستخدم طبقات حماية متعددة بدل الاعتماد على إخفاء الرابط فقط.</p>`)}
function openKnowledge(k){const data={karat:['اعرف عيار الذهب',`<p><b>24 قيراط:</b> أعلى نقاء شائع للذهب الاستثماري والسبائك.</p><p><b>21 قيراط:</b> من أشهر العيارات في المشغولات المصرية، ونسبة الذهب فيه أقل من 24.</p><p><b>18 قيراط:</b> يحتوي على نسبة ذهب أقل من 21، ويُستخدم كثيرًا في المشغولات.</p><p>كلما اختلف العيار اختلف سعر الجرام، لذلك نعرض السعر بحسب العيار بدل استخدام رقم واحد لكل المنتجات.</p>`],price:['كيف يُحسب السعر؟',`<p>في أبسط صورة: <b>قيمة الذهب = الوزن × سعر جرام العيار.</b></p><p>ثم قد تضاف المصنعية وأي إضافات أو رسوم مرتبطة بالمنتج.</p><p><b>مثال:</b> قطعة وزنها 5 جم عيار 21، وسعر جرام 21 هو 5,000 ج.م، فقيمة الذهب الخام 25,000 ج.م قبل المصنعية والإضافات.</p><p>في السبائك قد تكون المعادلة مختلفة بحسب المنتج والمصنعية والرسوم، ولذلك السعر النهائي يظهر على بطاقة المنتج.</p>`],saving:['ادخار الذهب',`<p>السبائك والجنيهات عادةً أوضح للعميل الذي يهتم بوزن الذهب نفسه، بينما المشغولات تجمع بين قيمة الذهب والتصميم والمصنعية.</p><p>قبل الشراء، قارن الوزن والعيار والمصنعية وسياسة إعادة الشراء.</p>`],verify:['تحقق من القطعة',`<p>إذا كانت القطعة مسجلة لدى المحل، يمكن استخدام كود المنتج أو QR للوصول إلى صفحة تحقق لا تكشف بيانات مالك القطعة.</p><p>وجود كود لا يعني وحده إثبات الملكية القانونية؛ التحقق يعتمد على سجل المحل والبيانات المرتبطة بالقطعة.</p>`]};const x=data[k]||data.price;openArticle(x[0],x[1])}
function openArticle(title,body){$('articleTitle').textContent=title;$('articleBody').innerHTML=body;$('articleModal').classList.add('open')}function closeArticle(){$('articleModal').classList.remove('open')}
function openVaultPurchase(){if(!requireCustomer('لشراء الذهب وربطه بالمحفظة لازم يكون عندك حساب.'))return;showSection('bullionCatalog');toast('اختار الشركة والوزن، وبعدها اضغط شراء السبيكة.')}
function requestVaultDelivery(){if(!requireCustomer('لازم تسجل الدخول أولًا لطلب استلام الذهب.'))return;toast('تم فتح طلب الاستلام لحسابك — المراجعة تتم من الإدارة.')}
const bullionCompanies=['BTC','Gold Era','SAM','MB','سليما جولد','Swiss Gold'];
const bullionWeights=[0.5,1,2.5,5,10,20,31.1,50,100,250,500,1000];
const coinCompanies=['BTC','SAM','MB','سامي عطية'];
const coinVariants={BTC:['جنيه BTC'],SAM:['جنيه SAM'],MB:['جنيه MB'],'سامي عطية':['جنيه سامي عطية']};
let selectedBullionCompany='BTC', selectedBullionWeight=10, selectedCoinCompany='BTC';
function renderBullionCatalog(company=selectedBullionCompany,weight=selectedBullionWeight){
 selectedBullionCompany=company; selectedBullionWeight=Number(weight);
 const companies=$('bullionCompanies'), weights=$('bullionWeights'), selected=$('bullionSelected'); if(!companies||!weights||!selected)return;
 companies.innerHTML=bullionCompanies.map(c=>`<button class="bullionCompany ${c===selectedBullionCompany?'active':''}" onclick="renderBullionCatalog('${escapeHtml(c)}',${selectedBullionWeight})">${escapeHtml(c)}</button>`).join('');
 weights.innerHTML=bullionWeights.map(w=>`<button class="weightBtn ${w===selectedBullionWeight?'active':''}" onclick="renderBullionCatalog('${escapeHtml(selectedBullionCompany)}',${w})">${fmt(w)} جم</button>`).join('');
 const price=(prices[24]||0)*selectedBullionWeight;
 const id=`bull-${selectedBullionCompany}-${selectedBullionWeight}`;
 selected.innerHTML=`<div class="bullionSelected"><div class="bullionPhoto"><span>${escapeHtml(selectedBullionCompany)}<br>${fmt(selectedBullionWeight)} جم</span></div><div class="bullionInfo"><span class="pill">${escapeHtml(selectedBullionCompany)}</span><h3>سبيكة ${escapeHtml(selectedBullionCompany)} — ${fmt(selectedBullionWeight)} جم</h3><div class="meta"><div>الوزن<br><b>${fmt(selectedBullionWeight)} جم</b></div><div>العيار<br><b>24</b></div><div>سعر البيع للعميل<br><b>${price?fmt(price)+' ج.م':'يتحدث الآن'}</b></div><div>الكود<br><b>${escapeHtml(id)}</b></div></div><div class="productBtns"><button class="saveBtn" onclick="toast('تم حفظ السبيكة في المفضلة')">🔖 حفظ</button><button class="reserveBtn" onclick="openBullionPurchase('${escapeHtml(id)}','سبيكة ${escapeHtml(selectedBullionCompany)} — ${fmt(selectedBullionWeight)} جم','${escapeHtml(selectedBullionCompany)}',${selectedBullionWeight},${price||0})">🛒 شراء السبيكة</button></div><div class="ownerHint">الصورة النهائية للسبيكة تُرفع من لوحة الإدارة لهذا الوزن؛ هنا نعرض معاينة مضغوطة فقط حتى لا نهدر مساحة الصفحة.</div></div></div>`;
 renderCoinCatalog();
}
function renderCoinCatalog(company=selectedCoinCompany){
 selectedCoinCompany=company; const companies=$('coinCompanies'), selected=$('coinSelected'); if(!companies||!selected)return;
 companies.innerHTML=coinCompanies.map(c=>`<button class="bullionCompany ${c===selectedCoinCompany?'active':''}" onclick="renderCoinCatalog('${escapeHtml(c)}')">${escapeHtml(c)}</button>`).join('');
 const name=coinVariants[selectedCoinCompany][0]; const price=(prices[21]||0)*8;
 selected.innerHTML=`<div class="bullionSelected"><div class="bullionPhoto"><span>${escapeHtml(selectedCoinCompany)}<br>جنيه ذهب</span></div><div class="bullionInfo"><span class="pill">${escapeHtml(selectedCoinCompany)}</span><h3>${escapeHtml(name)}</h3><div class="meta"><div>الوزن<br><b>8 جم</b></div><div>العيار<br><b>21</b></div><div>سعر البيع للعميل<br><b>${price?fmt(price)+' ج.م':'يتحدث الآن'}</b></div><div>الكود<br><b>COIN-${escapeHtml(selectedCoinCompany)}</b></div></div><div class="productBtns"><button class="saveBtn" onclick="toast('تم حفظ الجنيه في المفضلة')">🔖 حفظ</button><button class="reserveBtn" onclick="openBullionPurchase('coin-${escapeHtml(selectedCoinCompany)}','${escapeHtml(name)}','${escapeHtml(selectedCoinCompany)}',8,${price||0})">🛒 شراء الجنيه</button></div></div></div>`;
}
function openBullionPurchase(id,name,company,weight,price){if(!requireCustomer('لشراء السبيكة لازم يكون عندك حساب.'))return;const p={id,name,company,weight,karat:24,code:id,price};$('purchaseProductId').value='';$('purchaseSummary').innerHTML=`<div class="orderStat"><small>المنتج</small><b>${escapeHtml(name)}</b></div><div class="orderStat"><small>الشركة</small><b>${escapeHtml(company)}</b></div><div class="orderStat"><small>الوزن / العيار</small><b>${fmt(weight)} جم / 24</b></div><div class="orderStat"><small>السعر وقت الطلب</small><b>${price?fmt(price)+' ج.م':'سيحدد عند التحقق'}</b></div>`;$('purchaseAccountBox').innerHTML=`👤 الحساب: <b>${escapeHtml(getCustomer()?.name||'')}</b> • ${escapeHtml(getCustomer()?.email||'')} • سيتم ربط الطلب بهذا الحساب`;$('purchaseModal').classList.add('open');$('purchaseForm').dataset.bullion=JSON.stringify(p)}
const oldSubmit=$('purchaseForm').onsubmit;
on('purchaseForm','submit',async e=>{const bp=e.target.dataset.bullion;if(!bp)return; e.preventDefault();const p=JSON.parse(bp),fd=Object.fromEntries(new FormData(e.target).entries()),u=getCustomer();if(!u){delete e.target.dataset.bullion;closePurchase();return requireCustomer('سجّل حسابك أولًا.')}fd.customerName=u.name;fd.phone=u.phone;const order={id:'ORD-'+Date.now().toString().slice(-8),type:'شراء سبيكة',status:'pending_review',createdAt:new Date().toISOString(),customerRef:u.id,customerEmail:u.email,customerName:fd.customerName,phone:fd.phone,delivery:fd.delivery,notes:fd.notes,productId:0,productCode:p.id,productName:p.name,company:p.company,productType:'سبائك',style:'ذهب استثماري',karat:24,weight:p.weight,pricePerGram:prices[24]||0,total:p.price||0};orders.unshift(order);saveOrders();try{await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(order)})}catch(_){}delete e.target.dataset.bullion;closePurchase();e.target.reset();toast('تم إرسال طلب السبيكة للمراجعة — '+order.id);renderMyOrders()});
function refreshAccountButton(){const u=getCustomer();const b=document.querySelector('.accountBtn');if(b)b.textContent=u?'👤 حسابي':'🔐 تسجيل / محفظتي'}
// Hardening: expose core UI handlers explicitly and keep network work away from first paint.
window.openMenu=openMenu; window.closeMenu=closeMenu; window.toggleGroup=toggleGroup; window.showSection=showSection; window.scrollToId=scrollToId; window.openAccount=openAccount; window.closeAccount=closeAccount; window.openPurchase=openPurchase; window.closePurchase=closePurchase;
function checkSecretAdmin(){const q=new URLSearchParams(location.search);if(q.get('control')==='bushra-7f3c9b1e' || location.pathname==='/owner'){openAdmin();if(location.pathname==='/owner')history.replaceState({},'', '/');}}
window.addEventListener('error',e=>{try{console.error('BUSHRA UI ERROR',e.error||e.message)}catch(_){}});
checkSecretAdmin();
// UI-first bootstrap: nothing here should prevent menu/account buttons from working.
try{refreshAccountButton()}catch(_){}
try{renderVault()}catch(_){}
try{renderCatalog()}catch(_){}
try{renderBullionCatalog()}catch(_){}
try{renderBullion()}catch(_){}
try{renderReports()}catch(_){}
try{renderAdminOrders()}catch(_){}
try{updateClock()}catch(_){}
setInterval(()=>{try{updateClock()}catch(_){}},1000);
setTimeout(()=>{try{loadPrices()}catch(e){console.error(e)}},150);
setTimeout(()=>{try{loadWorld()}catch(e){console.error(e)}},300);
setInterval(()=>{try{loadPrices()}catch(e){console.error(e)}},120000);
setInterval(()=>{try{loadWorld()}catch(e){console.error(e)}},60000);
